services:
  - type: web
    name: exontogram
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: supersecretkeyforexontogram2026
      - key: PYTHON_VERSION
        value: 3.10.12
